Default: &defaults
  database: adam.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: adam_test.sqlite3
  <<: *defaults

Staging:
  database: adam_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: adam_production.sqlite3
  poolsize: 100
  <<: *defaults
